<script lang="ts">
	import EnquiryForm from './EnquiryForm.svelte';
	import Icon from './Icon.svelte';
	import SiteHeader from './SiteHeader.svelte';
	import WorkExample from './WorkExample.svelte';
	import { starterOffer, starterSetupPrice } from '../lib/starterOffer';

	let { baseUrl = '/', turnstileSiteKey = '', consultationMode = 'server' }: { baseUrl?: string; turnstileSiteKey?: string; consultationMode?: 'server' | 'email' } = $props();
	const sitePath = (path: string) => baseUrl + path.replace(/^\//, '');
	const enquiryPath = (service: string, source: string) => `${sitePath('/contact/')}?${new URLSearchParams({ service, source })}#consultation-form`;
</script>

<div class="page-shell">
	<a class="skip-link" href="#main-content">Skip to content</a>
	<SiteHeader {baseUrl} active="home" service="starter" source="home" />
	<main id="main-content">
		<span id="top" aria-hidden="true"></span>
		<section class="hero" aria-labelledby="hero-title"><div class="hero-inner page-width"><div><p class="eyebrow">For new businesses in Gippsland</p><h1 id="hero-title">Website, email and essential accounts. Set up together.</h1><p class="lead">A practical starter setup for a new small business, with one person to guide you through it.</p><p class="hero-price"><strong>{starterSetupPrice} setup.</strong> Domain, hosting and email subscriptions cost extra. <a href={sitePath('/start-a-business/#cost')}>See costs and scope</a></p><div class="actions"><a class="button" href={sitePath('/start-a-business/')}>See the starter offer <Icon name="arrowRight" size={22} /></a><a class="text-link" href="#consultation-form">Quick enquiry</a></div></div><div class="hero-art"><img class="note" src={sitePath('/images/illustrations/ideas-to-customers.webp')} width="768" height="750" alt="From ideas to customers" /><img class="photo" src={sitePath('/images/illustrations/new-business-storefront.webp')} width="1122" height="1402" alt="A New Business sign hanging in a shop window." fetchpriority="high" /></div></div></section>

		<section id="services" class="existing page-width" aria-labelledby="existing-title"><div id="other-services"><p class="eyebrow">Already trading?</p><h2 id="existing-title">Get help with what is getting in the way.</h2></div><nav aria-label="Services for existing businesses"><a href={sitePath('/websites/')}>Websites</a><a href={sitePath('/business-it/')}>Business IT</a><a href={sitePath('/security/')}>Account security</a></nav></section>

		<section id="included" class="offer-section"><div class="page-width offer-grid"><div><p class="eyebrow">Business starter setup</p><h2>A useful online presence without piecing it together yourself.</h2><p class="lead">The setup covers the core tools a small business needs to be found and answer customers professionally.</p><a class="text-link" href={sitePath('/start-a-business/')}>Check the full scope and responsibilities</a></div><div id="costs" class="offer-card"><p class="price"><span>Setup fee</span><strong>{starterSetupPrice}</strong></p><ul>{#each starterOffer.inclusions.slice(0, 4) as item}<li><Icon name="shieldCheck" size={22} /> <span>{item}</span></li>{/each}</ul><p class="annual-budget"><strong>{starterOffer.annualBudgetNote.display}</strong><span>{starterOffer.annualBudgetNote.description}</span><small>{starterOffer.annualBudgetNote.label}</small></p><p class="fine-print">{starterOffer.thirdPartyCosts}</p><p class="fine-print">{starterOffer.quoteNote}</p><a class="button" href="#consultation-form">Ask about the starter setup <Icon name="arrowRight" size={22} /></a></div></div></section>

		<section id="work" class="proof-section"><div class="page-width"><WorkExample {baseUrl} compact /><div class="proof-action"><p>Starting something similar?</p><a class="button" href={enquiryPath('starter', 'home')}>Ask about the starter setup <Icon name="arrowRight" size={22} /></a></div></div></section>

		<section id="process" class="process-section"><div class="page-width process-grid"><div><p class="eyebrow">How it works</p><h2>Start with the facts you already have.</h2></div><ol><li><span>1</span><div><h3>Tell us about the business</h3><p>A rough description, service details and any photos are enough for the first conversation.</p></div></li><li><span>2</span><div><h3>Approve a written quote</h3><p>We confirm the scope, costs, responsibilities and timing before work begins.</p></div></li><li><span>3</span><div><h3>Review and take over</h3><p>You give one consolidated round of feedback, then receive access and a walkthrough.</p></div></li></ol></div></section>

		<section id="contact" class="contact-section"><div class="page-width contact-grid"><div><p class="eyebrow">Quick enquiry</p><h2>Tell us what you're starting.</h2><p class="lead">A rough description is enough. We aim to reply within two business days and will confirm the scope in a written quote.</p><a class="phone-link" href="tel:0341488665">Prefer a call? (03) 4148 8665</a><p class="fine-print">Monday, Tuesday and Friday, 9am to 4pm.</p></div><EnquiryForm {baseUrl} {turnstileSiteKey} {consultationMode} defaultService="starter" source="home" returnPath={baseUrl} /></div></section>
	</main>
	<footer id="about"><a class="footer-brand" href={baseUrl}><img src={sitePath('/images/servo-ict-logo.png')} alt="" width="42" height="42" />Servo ICT · Gippsland</a><nav aria-label="Footer navigation"><a href={sitePath('/start-a-business/')}>Start a business</a><a href={sitePath('/about/')}>About</a><a href={sitePath('/blog/')}>Advice</a><a href={enquiryPath('starter', 'home')}>Contact</a><a href={sitePath('/privacy/')}>Privacy</a><a href="mailto:support@servoict.com">support@servoict.com</a></nav><span>© {new Date().getFullYear()} Servo ICT</span></footer>
</div>

<style>
	.page-shell{overflow:clip}.page-width{width:var(--content-width);margin-inline:auto}.skip-link{position:fixed;z-index:30;left:1rem;top:1rem;transform:translateY(-200%);padding:.8rem 1.2rem;background:var(--plastic);color:var(--ink);font-weight:700}.skip-link:focus{transform:translateY(0)}
	.hero,.offer-section,.proof-section{background-color:var(--plastic);border-bottom:1px solid var(--seam);box-shadow:inset 0 -1px 0 var(--edge)}.hero-inner{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(0,.85fr);gap:clamp(2rem,5vw,5rem);align-items:center;padding-block:var(--home-section-space)}
	.eyebrow{margin:0 0 1rem;color:var(--ink);font-size:.76rem;font-weight:700;letter-spacing:.13em;text-transform:uppercase}h1,h2,h3{margin:0}h1{font-size:clamp(2.75rem,5.4vw,5rem);line-height:1.05;letter-spacing:-.045em}h2{font-size:clamp(2rem,4vw,3.4rem);line-height:1.1;letter-spacing:-.04em}h3{font-size:1.12rem}.lead{max-width:38rem;margin:1.2rem 0 0;color:var(--muted);font-size:clamp(1.08rem,1.5vw,1.25rem);line-height:1.6}.actions{display:flex;flex-wrap:wrap;align-items:center;gap:1.2rem 1.8rem;margin-top:1.6rem}.button{display:inline-flex;align-items:center;justify-content:center;gap:1.2rem;min-height:54px;padding:.8rem 1.2rem;font-weight:700;text-decoration:none}.text-link,.phone-link{display:inline-flex;align-items:center;min-height:44px;font-weight:700}.hero-art{display:grid;grid-template-columns:minmax(0,.36fr) minmax(0,1fr);align-items:center;gap:1rem}.note{display:block;width:100%;height:auto;filter:grayscale(1);mix-blend-mode:multiply}.photo{display:block;width:100%;height:auto;aspect-ratio:4/5;object-fit:cover;border:1px solid var(--seam);border-radius:8px;box-shadow:var(--image-recess)}
	.hero-price{max-width:var(--reading-measure);margin:1.25rem 0 0;font-size:1rem;line-height:1.6}.hero-price strong{color:var(--ink)}.hero-price a{font-weight:700}
	.existing{display:grid;grid-template-columns:1fr 1fr;align-items:center;gap:3rem;padding-block:clamp(2.25rem,4vw,3.5rem)}.existing h2{font-size:clamp(1.6rem,3vw,2.4rem)}.existing nav{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:.5rem 2rem}.existing a{min-height:44px;display:inline-flex;align-items:center;font-weight:700}
	.offer-section{padding-block:var(--home-section-space);border-top:1px solid var(--seam)}.offer-grid{display:grid;grid-template-columns:minmax(0,.9fr) minmax(0,1.1fr);gap:clamp(3rem,7vw,7rem);align-items:start}.offer-grid>.offer-card{padding-left:clamp(1.5rem,4vw,4rem);border-left:1px solid var(--line)}.offer-grid .text-link{margin-top:1.2rem}.price{display:flex;flex-wrap:wrap;gap:.5rem 1rem;justify-content:space-between;align-items:baseline;margin:0 0 1.5rem;padding-bottom:1rem;border-bottom:1px solid var(--line)}.price span{font-weight:700}.price strong{font-size:clamp(2rem,4vw,3.2rem);letter-spacing:-.04em}.offer-card ul{display:grid;gap:1rem;margin:0;padding:0;list-style:none}.offer-card li{display:flex;align-items:flex-start;gap:.8rem;line-height:1.5}.offer-card li :global(svg){flex:0 0 auto}.annual-budget{display:grid;gap:.35rem;margin:1.5rem 0;padding:1rem 0;border-block:1px solid var(--line);line-height:1.55}.annual-budget strong{font-size:1.1rem}.annual-budget span,.annual-budget small,.fine-print{color:var(--muted)}.annual-budget small,.fine-print{font-size:.9rem;line-height:1.6}.offer-card .button{margin-top:1rem}
	.proof-section{padding-block:var(--section-space-compact)}.proof-action{display:flex;align-items:center;justify-content:space-between;gap:1.5rem;margin-top:clamp(2rem,4vw,3.5rem);padding-top:clamp(1.5rem,3vw,2.5rem);border-top:1px solid var(--line)}.proof-action p{margin:0;font-size:clamp(1.1rem,2vw,1.35rem);font-weight:700}.process-section,.contact-section{padding-block:var(--home-section-space)}.process-grid{display:grid;grid-template-columns:minmax(0,.75fr) minmax(0,1.25fr);gap:4rem}.process-grid ol{display:grid;gap:1.5rem;margin:0;padding:0;list-style:none}.process-grid li{display:grid;grid-template-columns:44px 1fr;gap:1rem;padding-bottom:1.5rem;border-bottom:1px solid var(--line)}.process-grid li>span{display:grid;place-items:center;width:42px;height:42px;border:1px solid var(--line);border-radius:7px;font-weight:700}.process-grid p{margin:.5rem 0 0;color:var(--muted);line-height:1.55}.contact-grid{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);gap:clamp(3rem,7vw,7rem)}
	footer{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:2rem;padding-block:3rem;font-size:.9rem}.footer-brand{display:flex;align-items:center;gap:.7rem;font-weight:700;text-decoration:none}.footer-brand img{filter:grayscale(1) brightness(0) invert(.79)}footer nav{display:flex;justify-content:center;flex-wrap:wrap;gap:.5rem 1.5rem}footer nav a{display:inline-flex;align-items:center;min-height:44px}
	@media(max-width:760px){.hero-inner,.existing,.offer-grid,.process-grid,.contact-grid{grid-template-columns:1fr}.hero-art{max-width:28rem}.existing{gap:1.5rem}.existing nav{justify-content:flex-start}.offer-grid{gap:2.5rem}.offer-grid>.offer-card{padding:0;border:0}.button{width:100%;justify-content:space-between}.proof-action{align-items:flex-start;flex-direction:column}.process-grid{gap:2.5rem}footer{grid-template-columns:1fr;align-items:start}footer nav{justify-content:flex-start}}
</style>
